services:
  - type: web
    name: socialbooster
    env: python
    buildCommand: |
      pip install -r backend/requirements.txt
      cd frontend && npm install && npm run build
      cd ../backend && python manage.py collectstatic --noinput
    startCommand: cd backend && gunicorn socialbooster.wsgi:application
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: socialbooster-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4

databases:
  - name: socialbooster-db
    databaseName: socialbooster
    user: socialbooster
