services:
  - type: web
    name: socialbooster
    env: python
    buildCommand: "pip install -r backend/requirements.txt && npm install --prefix frontend && npm run build --prefix frontend && mkdir -p backend/staticfiles && cp -r frontend/dist/* backend/staticfiles/ && cd backend && python manage.py collectstatic --noinput"
    startCommand: cd backend && gunicorn socialbooster.wsgi:application
    preDeployCommand: cd backend && python manage.py migrate
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
